In [1]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\prathmesh\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\prathmesh\anaconda3\lib\site-packages (from openpyxl) (2.0.0)

In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\prathmesh\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\prathmesh\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\prathmesh\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\prathmesh\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\prathmesh\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\prathmesh\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [9]:
import pandas as pd
import numpy as np

In [ ]:
data = [10, 20, 30, 40] # this is a list
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64

In [53]:
import pandas as pd  # Import the pandas library
#df = pd.read_csv(r"D:\download\NMD\python\DA 11\DA11 python\car_sales_india.csv")
df = pd.read_csv(r"D:\download\NMD\python\DA 11\DA11 python\car_sales_india.csv") # Read the CSV file into a DataFrame
print(df.head(10))

   Sale ID        Date Car Brand Car Model Fuel Type Transmission  \
0        1  2023-07-28     Honda     Amaze  Electric    Automatic
1        2  2023-07-30  Mahindra      Thar    Diesel       Manual
2        3  2023-07-30     Honda      City  Electric    Automatic
3        4  2023-02-12      Tata     Tiago  Electric    Automatic
4        5  2023-02-27     Honda     Amaze  Electric       Manual
5        6  2023-09-12     Honda      City    Diesel       Manual
6        7  2023-04-09     Honda     Amaze  Electric    Automatic
7        8  2023-01-24   Hyundai       i10  Electric       Manual
8        9  2023-07-07     Honda      Jazz    Petrol    Automatic
9       10  2023-01-24  Mahindra   Scorpio  Electric    Automatic

   Price (INR)       City Seller Type  Year of Manufacture  Mileage (km/l)  \
0      2636520    Chennai  Individual                 2018            19.6
1      1067639     Mumbai      Dealer                 2022            17.3
2      2832014  Bangalore      Dealer                 2019            13.6
3      2636617     Mumbai  Individual                 2016            16.3
4      2501019      Delhi      Dealer                 2022            21.1
5      2522517  Bangalore      Dealer                 2020            21.2
6      1763668      Delhi      Dealer                 2023            22.6
7       781014     Mumbai  Individual                 2016            10.6
8       333902      Delhi      Dealer                 2020            11.2
9       690609      Delhi      Dealer                 2020            11.0

   Engine Capacity (cc)
0                  1200
1                  1500
2                  1000
3                  1200
4                  1000
5                  1500
6                  2000
7                  2500
8                  2000
9                  1800

In [ ]:
df.tail()  # last 5 data

,Sale ID,Date,Car Brand,Car Model,Fuel Type,Transmission,Price (INR),City,Seller Type,Year of Manufacture,Mileage (km/l),Engine Capacity (cc)
495,496,2023-12-03,Hyundai,Verna,CNG,Automatic,1798782,Mumbai,Dealer,2020,23.4,1500
496,497,2023-01-13,Hyundai,i10,Petrol,Automatic,505073,Hyderabad,Dealer,2016,11.1,1800
497,498,2023-03-12,Tata,Harrier,Electric,Automatic,1459012,Hyderabad,Dealer,2015,12.7,1200
498,499,2023-12-21,Hyundai,Creta,Petrol,Automatic,2512166,Hyderabad,Individual,2020,13.1,1800
499,500,2023-11-20,Maruti,Dzire,Electric,Automatic,977102,Hyderabad,Dealer,2016,13.3,1800

In [ ]:
df.info()   # give info about data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Sale ID               500 non-null    int64
 1   Date                  500 non-null    object
 2   Car Brand             500 non-null    object
 3   Car Model             500 non-null    object
 4   Fuel Type             500 non-null    object
 5   Transmission          500 non-null    object
 6   Price (INR)           500 non-null    int64
 7   City                  500 non-null    object
 8   Seller Type           500 non-null    object
 9   Year of Manufacture   500 non-null    int64
 10  Mileage (km/l)        500 non-null    float64
 11  Engine Capacity (cc)  500 non-null    int64
dtypes: float64(1), int64(4), object(7)
memory usage: 47.0+ KB

In [ ]:
df.describe()  # its give summary od mathematical data

,Sale ID,Price (INR),Year of Manufacture,Mileage (km/l),Engine Capacity (cc)
count,500.000000,5.000000e+02,500.000000,500.000000,500.00000
mean,250.500000,1.715120e+06,2019.066000,17.303400,1671.60000
std,144.481833,8.084176e+05,2.622097,4.250805,502.25288
min,1.000000,3.065960e+05,2015.000000,10.000000,1000.00000
25%,125.750000,9.786890e+05,2017.000000,13.500000,1200.00000
50%,250.500000,1.765048e+06,2019.000000,17.200000,1500.00000
75%,375.250000,2.465958e+06,2021.000000,21.100000,2000.00000
max,500.000000,2.998496e+06,2023.000000,25.000000,2500.00000

In [60]:
df.isnull().sum()  # its  give  sum of null value

Sale ID                 0
Date                    0
Car Brand               0
Car Model               0
Fuel Type               0
Transmission            0
Price (INR)             0
City                    0
Seller Type             0
Year of Manufacture     0
Mileage (km/l)          0
Engine Capacity (cc)    0
dtype: int64

In [ ]:
d= d.drop_duplicates() #
print(d)

        ID          Name           Age       Location            Join Date  \
0        1          Mike            35       New York  2020-06-05 00:00:00
1        2         Sarah            29       New York  2021-05-12 00:00:00
2        3  Not Avalible           NaN        Chennai  2020-06-05 00:00:00
3        4       Jane D.            29          Delhi  2021-05-12 00:00:00
4        5         John             25  Mumbai, India  2021-05-12 00:00:00
...    ...           ...           ...            ...                  ...
9595  9596         John             25         London  2020-06-05 00:00:00
9596  9597  Not Avalible  Not Avalible         London  2023-07-07 00:00:00
9597  9598  Not Avalible            35       New York  2021-07-11 00:00:00
9598  9599          Mike            30      Bangalore  2023-05-06 00:00:00
9599  9600         Sarah  Not Avalible        Chennai  2023-07-07 00:00:00

            Salary      Department               Email         Phone  \
0            50000              HR  jane.d@example.net    0000000000
1            45000       Marketing                 NaN    9876543210
2     Not Avalible              HR    john@example.com  Not Avalible
3            45000              HR  jane.d@example.net    0000000000
4            58000  Human Resource        Not Avalible  Not Avalible
...            ...             ...                 ...           ...
9595         45000         Finance  jane.d@example.net     999888777
9596         58000    Not Avalible                 NaN    1234567890
9597         45000         Finance  jane.d@example.net  Not Avalible
9598  Not Avalible         Finance        Not Avalible    1234567890
9599         52000           Sales  jane.d@example.net  Not Avalible

        Experience  ...   Nationality   Has Vehicle  Vehicle Type  \
0                3  ...       British           Yes           Car
1     Not Avalible  ...       British           Yes  Not Avalible
2                3  ...      American           Yes          Bike
3                5  ...        Indian           Yes           Car
4                5  ...      American  Not Avalible          Bike
...            ...  ...           ...           ...           ...
9595  Not Avalible  ...      American           Yes           Car
9596             4  ...  Not Avalible  Not Avalible  Not Avalible
9597             4  ...  Not Avalible           Yes         Truck
9598             1  ...  Not Avalible  Not Avalible          Bike
9599             4  ...      American  Not Avalible          Bike

       Blood Group        Height        Weight Preferred Shift     Work Mode  \
0               O-           6ft           NaN         Evening        Remote
1               B+           6ft           NaN         Evening  Not Avalible
2               A+  Not Avalible            65    Not Avalible        Onsite
3              AB+           6ft           NaN    Not Avalible  Not Avalible
4     Not Avalible           6ft          70kg           Night  Not Avalible
...            ...           ...           ...             ...           ...
9595  Not Avalible         5'5ft          70kg    Not Avalible  Not Avalible
9596            B+         5'5ft            65           Night  Not Avalible
9597            B+  Not Avalible            65           Night  Not Avalible
9598            B+  Not Avalible          70kg         Morning  Not Avalible
9599            O-         5'8ft  Not Avalible         Evening        Onsite

     Languages Known Employee Code
0       Not Avalible        EMP001
1            English  Not Avalible
2                NaN  Not Avalible
3       Not Avalible        EMP123
4       Not Avalible        EMP001
...              ...           ...
9595    Not Avalible  Not Avalible
9596    Not Avalible        EMP123
9597         Marathi  Not Avalible
9598    Not Avalible        EMP002
9599             NaN  Not Avalible

[9600 rows x 25 columns]

In [67]:
# Sample data as a dictionary
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "Los Angeles", "Chicago"]
}
# Create a DataFrame from the dictionary
df = pd.DataFrame(data)
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [ ]:
df.to_csv("hi.csv") # its data store in csv file

In [61]:
import pandas as pd
d = pd.read_excel(r"D:\download\NMD\python\DA 11\DA11 python\Practice_sheet unclean.xlsx")
print(d.head(100))

     ID          Name           Age       Location            Join Date  \
0     1          Mike            35       New York  2020-06-05 00:00:00
1     2         Sarah            29       New York  2021-05-12 00:00:00
2     3  Not Avalible           NaN        Chennai  2020-06-05 00:00:00
3     4       Jane D.            29          Delhi  2021-05-12 00:00:00
4     5         John             25  Mumbai, India  2021-05-12 00:00:00
..  ...           ...           ...            ...                  ...
95   96          John  Not Avalible         London  2021-07-11 00:00:00
96   97          John            25       New York  2021-05-12 00:00:00
97   98          John  Not Avalible       New York  2022-11-01 00:00:00
98   99       Jane D.  Not Avalible          Delhi  2021-05-12 00:00:00
99  100          Sara  Not Avalible         London  2020-06-05 00:00:00

          Salary      Department               Email         Phone  \
0          50000              HR  jane.d@example.net    0000000000
1          45000       Marketing                 NaN    9876543210
2   Not Avalible              HR    john@example.com  Not Avalible
3          45000              HR  jane.d@example.net    0000000000
4          58000  Human Resource        Not Avalible  Not Avalible
..           ...             ...                 ...           ...
95         45000    Not Avalible    john@example.com    9876543210
96         61000              HR                 NaN    0000000000
97         52000  Human Resource                 NaN  Not Avalible
98         50000              HR                 NaN     999888777
99  Not Avalible           Sales  jane.d@example.net    9876543210

      Experience  ...   Nationality   Has Vehicle  Vehicle Type   Blood Group  \
0              3  ...       British           Yes           Car            O-
1   Not Avalible  ...       British           Yes  Not Avalible            B+
2              3  ...      American           Yes          Bike            A+
3              5  ...        Indian           Yes           Car           AB+
4              5  ...      American  Not Avalible          Bike  Not Avalible
..           ...  ...           ...           ...           ...           ...
95             3  ...        Indian           Yes  Not Avalible  Not Avalible
96             1  ...  Not Avalible  Not Avalible  Not Avalible            B+
97             1  ...       British  Not Avalible          Bike           AB+
98  Not Avalible  ...  Not Avalible  Not Avalible          Bike            O-
99  Not Avalible  ...        Indian  Not Avalible         Truck  Not Avalible

          Height        Weight Preferred Shift     Work Mode Languages Known  \
0            6ft           NaN         Evening        Remote    Not Avalible
1            6ft           NaN         Evening  Not Avalible         English
2   Not Avalible            65    Not Avalible        Onsite             NaN
3            6ft           NaN    Not Avalible  Not Avalible    Not Avalible
4            6ft          70kg           Night  Not Avalible    Not Avalible
..           ...           ...             ...           ...             ...
95  Not Avalible  Not Avalible    Not Avalible  Not Avalible         Marathi
96           6ft          70kg    Not Avalible        Remote         English
97         5'8ft           NaN    Not Avalible        Onsite         English
98  Not Avalible  Not Avalible    Not Avalible        Onsite    Not Avalible
99           6ft            65    Not Avalible  Not Avalible    Not Avalible

   Employee Code
0         EMP001
1   Not Avalible
2   Not Avalible
3         EMP123
4         EMP001
..           ...
95  Not Avalible
96  Not Avalible
97        EMP002
98  Not Avalible
99        EMP001

[100 rows x 25 columns]

In [62]:
d.describe()

                ID
count  9600.000000
mean   4800.500000
std    2771.425626
min       1.000000
25%    2400.750000
50%    4800.500000
75%    7200.250000
max    9600.000000

In [7]:
import pandas as pd  # Import the pandas library
df = pd.read_excel(r"D:\download\NMD\python\DA 11\DA11 python\Practice_sheet unclean.xlsx")
 # Read the CSV file into a DataFrame
print(df.head(10))

   ID          Name  Age       Location            Join Date        Salary  \
0   1          Mike   35       New York  2020-06-05 00:00:00         50000
1   2         Sarah   29       New York  2021-05-12 00:00:00         45000
2   3  Not Avalible  NaN        Chennai  2020-06-05 00:00:00  Not Avalible
3   4       Jane D.   29          Delhi  2021-05-12 00:00:00         45000
4   5         John    25  Mumbai, India  2021-05-12 00:00:00         58000
5   6       Jane D.   40   Not Avalible  2023-06-05 00:00:00         52000
6   7          John   30  Mumbai, India  2020-06-05 00:00:00         45000
7   8  Not Avalible   29       New York  2021-07-11 00:00:00         52000
8   9          Mike   25      Bangalore  2021-05-12 00:00:00         45000
9  10          Mike   29         London  2021-05-12 00:00:00         45000

       Department               Email         Phone    Experience  ...  \
0              HR  jane.d@example.net    0000000000             3  ...
1       Marketing                 NaN    9876543210  Not Avalible  ...
2              HR    john@example.com  Not Avalible             3  ...
3              HR  jane.d@example.net    0000000000             5  ...
4  Human Resource        Not Avalible  Not Avalible             5  ...
5           Sales   sarah@company.com  Not Avalible  Not Avalible  ...
6              HR        Not Avalible    0000000000             2  ...
7    Not Avalible  jane.d@example.net  Not Avalible  Not Avalible  ...
8    Not Avalible    mike123@work.org    9876543210  Not Avalible  ...
9         Finance  jane.d@example.net    9876543210             2  ...

    Nationality   Has Vehicle  Vehicle Type   Blood Group        Height  \
0       British           Yes           Car            O-           6ft
1       British           Yes  Not Avalible            B+           6ft
2      American           Yes          Bike            A+  Not Avalible
3        Indian           Yes           Car           AB+           6ft
4      American  Not Avalible          Bike  Not Avalible           6ft
5  Not Avalible            No          Bike            O-  Not Avalible
6  Not Avalible  Not Avalible  Not Avalible  Not Avalible         5'8ft
7       British           Yes           Car  Not Avalible         5'8ft
8  Not Avalible           Yes          Bike           AB+           6ft
9      American  Not Avalible           Car            B+  Not Avalible

         Weight Preferred Shift     Work Mode Languages Known Employee Code
0           NaN         Evening        Remote    Not Avalible        EMP001
1           NaN         Evening  Not Avalible         English  Not Avalible
2            65    Not Avalible        Onsite             NaN  Not Avalible
3           NaN    Not Avalible  Not Avalible    Not Avalible        EMP123
4          70kg           Night  Not Avalible    Not Avalible        EMP001
5  Not Avalible         Morning  Not Avalible         English  Not Avalible
6  Not Avalible         Evening        Hybrid         Marathi        EMP001
7  Not Avalible    Not Avalible        Remote         English        EMP001
8  Not Avalible    Not Avalible  Not Avalible           Hindi        EMP123
9          70kg    Not Avalible        Onsite             NaN        EMP002

[10 rows x 25 columns]

In [ ]:
import pandas as pd
import sqlite3

# Connect database
conn = sqlite3.connect("employees.db")

# Read SQL file

with open(r"D:\download\NMD\python\DA 11\DA11 python\employees Database.sql", "r") as file:
     sql_script = file.read()
     print(df.head())

   ID          Name  Age       Location            Join Date        Salary  \
0   1          Mike   35       New York  2020-06-05 00:00:00         50000
1   2         Sarah   29       New York  2021-05-12 00:00:00         45000
2   3  Not Avalible  NaN        Chennai  2020-06-05 00:00:00  Not Avalible
3   4       Jane D.   29          Delhi  2021-05-12 00:00:00         45000
4   5         John    25  Mumbai, India  2021-05-12 00:00:00         58000

       Department               Email         Phone    Experience  ...  \
0              HR  jane.d@example.net    0000000000             3  ...
1       Marketing                 NaN    9876543210  Not Avalible  ...
2              HR    john@example.com  Not Avalible             3  ...
3              HR  jane.d@example.net    0000000000             5  ...
4  Human Resource        Not Avalible  Not Avalible             5  ...

  Nationality   Has Vehicle  Vehicle Type   Blood Group        Height Weight  \
0     British           Yes           Car            O-           6ft    NaN
1     British           Yes  Not Avalible            B+           6ft    NaN
2    American           Yes          Bike            A+  Not Avalible     65
3      Indian           Yes           Car           AB+           6ft    NaN
4    American  Not Avalible          Bike  Not Avalible           6ft   70kg

  Preferred Shift     Work Mode Languages Known Employee Code
0         Evening        Remote    Not Avalible        EMP001
1         Evening  Not Avalible         English  Not Avalible
2    Not Avalible        Onsite             NaN  Not Avalible
3    Not Avalible  Not Avalible    Not Avalible        EMP123
4           Night  Not Avalible    Not Avalible        EMP001

[5 rows x 25 columns]

TypeError: 'NoneType' object is not iterable